site_name: Evan's Dev Note
nav:
        - '현재 편집중...': nodejs.md
        - 프로젝트 1 CHAT:
                  - '- chat -': _chat.md
        - 프로젝트 2 Metaverse:
                  - '- metaverse -': _metaverse.md
        - 프로젝트 3 MMO:
                  - '- mmo -': _mmo.md
        - HTML:
                  - '- html -': html.md
                  - '- css -': css.md
        - 자바스크립트:
                  - '- javascript -': javascript.md
                  - '- typescript -': typescript.md
                  - '- rxjs -': rxjs.md
                  - '- jquery -': jquery.md
        - 노드.JS:
                  - '- node.js -': nodejs.md
                  - '- express -': express.md
                  - '- socketio -': socketio.md
        - 프론트엔드:
                  - '- Frontend -': frontend.md
                  - '- React.js -': reactjs.md
                  - '- Vue.js -': vuejs.md
                  - '- flutter -': flutter.md
        - WEBGL:
                  #   - '- PlayCanvas -': playcanvas.md
                  - '- three.js -': threejs.md
                  - '- blueprint3d.js -': blueprint3d.md
        # - Typescript: index.md
        - 파이썬:
                  - '- python -': python.md
        # - Pandas: index.md
        # - Pytorch: index.md

        # - SpringBoot: index.md
        # - Unity3D: index.md
        # - PHP: index.md

        # - Intellij: index.md
        # - Pycharm: index.md
        # - Rider: index.md
        - '씨#':
                  - '- c# -': csharp.md
        - 유니티3D:
                  - '- unity3d -': unity3d.md
                  - '- websocket -': unity3d_websocket.md
        - 인공지능:
                  - '- chatbot -': chatbot.md
        - 인프라:
                  - '- aws -': aws.md
                  - '- azure -': azure.md
                  - '- linux -': linux.md
                  - '- docker -': docker.md
                  - '- kubernetes -': kubernetes.md
        - 알고리즘:
                  - '- cryptography -': crypto.md
        - 유틸:
                  - '- mkdocs -': mkdocs.md
                  - '- jekyll -': jekyll.md
                  - '- git -': git.md
                  - '- chocolatey -': chocolatey.md
        - 편집기:
                  - '- Intellij -': intellij.md
                  - '- vscode -': vscode.md
                  - '- blender -': blender.md
        - 번들러:
                  - '- webpack -': webpack.md
                  - '- parcel -': parcel.md
                  - '- grunt -': grunt.md
        - 기타:
                  - '- 기타툴': tools.md
                  - '- 각종에러 -': errors.md
                  - '- 용어들 -': terms.md
                  - '- 벤치마크 -': benchmark.md
                  - '- 단축키 -': shortcuts.md
                  - '- 참고사이트 -': sites.md
                  #   - '- 기타 -': etc.md
        - ABOUT: about.md
          #   - '- TO-DO -': todo.md

theme:
        name: readthedocs
# highlightjs: true
# name: mkdocs
# shortcuts:
#   help: 191 # ?
#   next: 78 # n
#   previous: 80 # p
#   search: 83 # s
# site_description: 검색 메타
# site_author: 검색 메타
google_analytics: ['UA-36723568-3', 'mkdocs.org']

plugins:
        - search: false
#   - mkpdfs
#   - company: "Evan's Dev Note"
#   - author: 'Evan'
#   - toc_title: TOC
#   design: mkpdfs-design-sample/report.css
