site_name: Evan's IT Note
nav:
  - HTML:
      - "- HTML": html.md
      - "- CSS": css.md
  - TYPESCRIPT:
      - "- Typescript": typescript.md
  - NODE.JS:
      - "- NodeJS": nodejs.md
  # - Vue.js: index.md
  # - Typescript: index.md
  - PYTHON:
      - "- Python": python.md
  # - Pandas: index.md
  # - Pytorch: index.md

  # - SpringBoot: index.md
  # - Unity3D: index.md
  # - PHP: index.md

  # - Intellij: index.md
  # - Pycharm: index.md
  # - Rider: index.md

  - UNITY3D:
      - "- Unity3D": unity3d.md
  # - MMORPG: index.md
  - PROJECT 1 CHAT:
      - "- Chat": chat.md
  - PROJECT 2 MMO:
      - "- MMO": mmo.md
  - System:
      - "- AWS": aws.md
      - "- Azure": azure.md
      - "- Linux": linux.md
  - TOOLS:
      - "- Mkdocs": mkdocs.md
      - "- Jekyll": jekyll.md
      - "- Git": git.md
      - "- Chocolatey": chocolatey.md
      - "- VSCode": vscode.md
      - "- Docker": docker.md
  - ETC:
      - "- 참고 사이트": sites.md
      - "- 참고 단축키": shortcuts.md
      - "- ABOUT ME": about.md
      - "- TO-DO": todo.md

theme:
  name: readthedocs
  # highlightjs: true
  # name: mkdocs
  # shortcuts:
  #   help: 191 # ?
  #   next: 78 # n
  #   previous: 80 # p
  #   search: 83 # s
# site_description: 검색 메타
# site_author: 검색 메타
google_analytics: ["UA-36723568-3", "mkdocs.org"]

plugins:
  - search
